version: '3.8'
services:
  api:
    build: .
    ports:
      - "4500:4500"
    environment:
      - PORT=4500
      - MONGO_URI=mongodb://mongo:27017/expense-tracker-main
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_URL=${CLIENT_URL}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX}
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
